# Generated by Django 4.2.13 on 2024-05-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
