# Generated by Django 4.2.13 on 2024-05-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
