# Generated by Django 4.2.13 on 2024-05-23 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0007_alter_marketplaceprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
