# Generated by Django 4.2.13 on 2024-05-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='phone_number',
            field=models.CharField(default='(000) 000-0000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
